### PR TITLE
Bump compojure-api to 0.24.5.

### PR DESCRIPTION
**Pull request by ianmcorvidae**
Moving to 1.0+ will require a bit of work (https://github.com/metosin/compojure-api/wiki/Migration-Guide-to-1.0.0), but this is just bugfixes. I haven't tested everything which uses this intensively but everything compiles and the changes are pretty minimal (starting at https://github.com/metosin/compojure-api/blob/master/CHANGELOG.md#0245-1712016 and below).

### CODE REVIEW

**Comment by psarando** [comment]
The apps project was left out.

**Comment by ianmcorvidae** [comment]
Good catch @psarando -- I've force-pushed with it included. Must have skipped a line on friday.

**Comment by dennisroberts71** [comment]
Looks good to me. :shipit:

**Comment by psarando** [comment]
Looks good now :shipit:

**Pull request merged**
