### PR TITLE
iRODS AMQP broker can now be on separate host

### PR DESCRIPTION
**Pull request by tedgin**
This is a pull request against the master branch to bring the AMQP broker configuration specified in ansible scripts inline with what's currently in prod.  There are corresponding changes in the `irods_amqp_cfg` branch of the `de-ansible` private repo.

### CODE REVIEW

**Comment by ianmcorvidae** [comment]
Looks straightforward to me. :shipit:

**Comment by ianmcorvidae** [comment]
actually, one question -- do we want to potentially handle the case of having a different username/password, too? this just makes it work with a different host/port, but requires the users/passwords to match.

**Comment by tedgin** [comment]
I think we do want to handle that case, but I am trying to do the minimal fix against the master branch.  Once the changes are pushed down into the dev branch, I was planning to make the rest of them there.  I am expecting there to be more changes to add, but I haven't given any thought to what those could be.

Does this seem ok, or would it be more clear to have the username and password changes be part of this merge?

**Comment by ianmcorvidae** [comment]
That seems fine, makes sense.

**Pull request merged**
