### PR TITLE
Core 7009

### PR DESCRIPTION
**Pull request by dennisroberts71**

### CODE REVIEW

**Comment by psarando** [comment]
Just looked over this quickly, but I didn't catch any obvious errors :shipit:

**Comment by dennisroberts71** [comment]
Cool, thanks! :+1:

**Comment by strootman** [comment]
I looked it over, and it looks ok. But, someone who lives in this code more should look it over.

**Comment by ianmcorvidae** [comment]
Meant to say earlier, I looked at this on the way to work and I think it looks ready. :shipit:

**Pull request merged**
