### PR TITLE
CORE-7546: register newly submitted analyses in Grouper and give the subm…

### PR DESCRIPTION
**Pull request by dennisroberts71**
…itter ownership permission

### CODE REVIEW

**Comment by ianmcorvidae** [comment]
Straightforward as usual, seems to work the same way as apps :ship:

**Comment by psarando** [comment]
Ah, I was confused, the commit and this PR description say `register newly submitted apps`, but isn't this change for analyses?

**Comment by ianmcorvidae** [comment]
Oh, that's a good point. It might be nice to fix up the commit message to say analyses as well (given that's where the PR description came from)

**Comment by psarando** [comment]
Other than fixing the commit message, the changes look good :+1:

**Comment by dennisroberts71** [comment]
Heh, hanks for catching the broken commit message. That's fixed now. Thanks for the reviews.

**Pull request merged**
